import { useEffect, useState } from "react";
import Head from "next/head";
import Filter from "../components/Filter";
import Search from "../components/Search";
import Nav from "../components/Nav";
import Card from "../components/Card";

interface Country {
  name: {
    common: string;
  };
  flags: {
    png: string;
  };
  population: number;
  region: string;
  capital: string;
}

export default function Home() {
  const [filter, setFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [data, setData] = useState<Country[]>([]);

  useEffect(() => {
    if (filter === "all") {
      fetch("https://restcountries.com/v3.1/all")
        .then((res) => res.json())
        .then((data) => {
          setData(data);
        });
    } else {
      fetch(`https://restcountries.com/v3.1/region/${filter}`)
        .then((res) => res.json())
        .then((data) => {
          setData(data);
        });
    }
  }, [filter]);

  useEffect(() => {
    if (search === "") {
      fetch("https://restcountries.com/v3.1/all")
        .then((res) => res.json())
        .then((data) => {
          setData(data);
        });
    } else {
      fetch(`https://restcountries.com/v3.1/name/${search}`)
        .then((res) => res.json())
        .then((data) => {
          setData(data);
        });
    }
  }, [search]);

  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="w-full lg:max-w-6xl mx-auto px-4 xl:px-0">
        <div className="search-bar py-6 flex flex-col lg:flex-row items-center justify-between gap-y-4">
          <Search setSearch={setSearch} />
          <Filter setFilter={setFilter} />
        </div>
        <div className="countries pb-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 grid-rows-1 gap-y-4 md:gap-8 xl:gap-12">
            {data.map((country, index: number) => (
              <Card key={index} country={country} />
            ))}
          </div>
        </div>
      </main>
      <footer></footer>
    </>
  );
}
