import { useEffect, useState } from "react";
import Head from "next/head";
import Filter from "../components/Filter";
import Search from "../components/Search";
import Nav from "../components/Nav";
import Card from "../components/Card";

interface Country {
  name: {
    common: string;
  };
  flags: {
    png: string;
  };
  population: number;
  region: string;
  capital: string;
}

export default function Home() {
  const [filter, setFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [data, setData] = useState<Country[]>([]);

  useEffect(() => {
    const fetchCountry = async () => {
      const res = await fetch(`https://restcountries.com/v3.1/all`);
      const resData = await res.json();
      setData(resData);
    };
    fetchCountry();
  }, []);

  // useEffect(() => {
  //   if (filter === "all") {
  //     fetch("https://restcountries.com/v3.1/all")
  //       .then((res) => res.json())
  //       .then((data) => {
  //         setData(data);
  //       });
  //   } else {
  //     fetch(`https://restcountries.com/v3.1/region/${filter}`)
  //       .then((res) => res.json())
  //       .then((data) => {
  //         setData(data);
  //       });
  //   }
  // }, [filter]);

  // useEffect(() => {
  //   if (search === "") {
  //     fetch("https://restcountries.com/v3.1/all")
  //       .then((res) => res.json())
  //       .then((data) => {
  //         setData(data);
  //       });
  //   } else {
  //     fetch(`https://restcountries.com/v3.1/name/${search}`)
  //       .then((res) => res.json())
  //       .then((data) => {
  //         setData(data);
  //       });
  //   }
  // }, [search]);

  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        <div className="search-bar w-full lg:max-w-6xl mx-auto py-6 px-4 lg:px-0 flex flex-col lg:flex-row items-center justify-between">
          <Search />
          <Filter />
        </div>
        <div className="countries w-full lg:max-w-6xl mx-auto py-6 px-4 lg:px-0">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {data.map((country, index: number) => (
              <Card key={index} country={country} />
            ))}
          </div>
        </div>
      </main>
      <footer></footer>
    </>
  );
}
